{
 "title": "Spark",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "exec CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"spark\",container=\"spark-kubernetes-executor\"}[30s])) by (pod,instance)",
     "legendFormat": "{{ pod }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "exec CPU stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"spark\",container=\"spark-kubernetes-executor\"}[30s])) by (pod,instance)",
     "legendFormat": "{{ pod }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "exec MEM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"spark\",container=\"spark-kubernetes-executor\"}) by (pod,instance)",
     "legendFormat": "{{ pod }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "exec MEM stack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"spark\",container=\"spark-kubernetes-executor\"}) by (pod,instance)",
     "legendFormat": "{{ pod }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"spark\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{namespace=\"spark\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "non-exec CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"spark\",pod!~\".+-exec-.+\"}[30s])) by (pod,instance)",
     "legendFormat": "{{ instance }} @ {{ pod }}"
    }
   ]
  },
  {
   "title": "non-exec MEM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"spark\",pod!~\".+-exec-.+\"}) by (pod,instance)",
     "legendFormat": "{{ instance }} @ {{ pod }}"
    }
   ]
  },
  {
   "title": "MEM swap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{namespace=\"spark\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}