grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin
      hide_version: true
    dashboards:
      default_home_dashboard_path: /var/lib/grafana/dashboards/default/kubernetes.json
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://monitor-prometheus-server.monitor.svc.cluster.local:80
        isDefault: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: default
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/default

prometheus:
  pushgateway:
    enabled: false
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    global:
      scrape_interval: 10s
      scrape_timeout: 5s
    service:
      retention: 3d
    persistentVolume:
      enabled: false
    extraConfigmapMounts:
      - name: eth-sd
        mountPath: /mnt
        configMap: eth-sd
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: eth-nodes
          metrics_path: /debug/metrics/prometheus
          file_sd_configs:
            - files:
              - /mnt/eth-targets.json
        - job_name: kubernetes-nodes-cadvisor
          scrape_interval: 10s
          scrape_timeout: 5s
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
          metric_relabel_configs:
            - action: replace
              source_labels: [id]
              regex: '^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$'
              target_label: rkt_container_name
              replacement: '${2}-${1}'
            - action: replace
              source_labels: [id]
              regex: '^/system\.slice/(.+)\.service$'
              target_label: systemd_service_name
              replacement: '${1}'

